CREATE OR REPLACE PROCEDURE TMS.TMS_PARTNERPAYABLDT_LOAD
(
  v_PAYABLEDATE IN TIMESTAMP,
  v_PAYABLETOPARTNERID IN  TMS_PAYABLETOPARTNER.PAYABLETOPARTNERID%TYPE,
  v_PARTNERID IN NUMBER DEFAULT NULL,
  v_STOREID IN VARCHAR2 DEFAULT NULL,
  v_Out OUT SYS_REFCURSOR
)
AS 
  v_START_DATE TIMESTAMP;
  v_END_DATE TIMESTAMP;
  t_TMSCONFIGVALUE VARCHAR2(2000);
BEGIN
  v_START_DATE := TRUNC(v_PAYABLEDATE, 'MM');
  v_END_DATE := ADD_MONTHS(v_START_DATE, 1);
  t_TMSCONFIGVALUE := TMS.GETTMSCONFIGVALUE('SOTYPE_WARRANTTY_GETAREAMANAGER');

  OPEN v_Out FOR
  WITH 
  -- Hợp đồng theo khu vực
  SA (SERVICEAGREEMENTID, PARTNERID, FEEAPPENDIXID, PNSERVICEPRICETABLEID, AREAID, rn) AS (
    SELECT * FROM (
      SELECT sa.SERVICEAGREEMENTID, sa.PARTNERID, saa.FEEAPPENDIXID, saa.PNSERVICEPRICETABLEID,
             sarea.AREAID,
             ROW_NUMBER() OVER (PARTITION BY sa.PARTNERID, sarea.AREAID ORDER BY saa.APPLYFROMDATE DESC) AS rn
      FROM TMS.TMS_SERVICEAGREEMENT sa
      JOIN TMS.TMS_SERVICEAGREEMENT_AREA sarea ON sa.SERVICEAGREEMENTID = sarea.SERVICEAGREEMENTID
      JOIN TMS.TMS_SERVICEAGREEMENT_APPENDIX saa ON sa.SERVICEAGREEMENTID = saa.SERVICEAGREEMENTID
      WHERE sa.ISDELETED = 0 AND sa.ISACTIVED = 1
        AND sarea.ISDELETED = 0 AND sarea.ISACTIVED = 1
        AND saa.ISDELETED = 0 AND saa.ISACTIVED = 1
        AND sa.SIGNEDDATE < v_END_DATE
        AND NVL(sa.EXTENDEDDATE, sa.EXPIREDDATE) >= v_START_DATE
        AND saa.APPLYTODATE >= v_START_DATE AND saa.APPLYFROMDATE < v_END_DATE
        AND NOT EXISTS (
          SELECT 1 FROM TMS.TMS_SERVICEAGREEMENT_STORE sas
          WHERE sas.SERVICEAGREEMENTID = sa.SERVICEAGREEMENTID
            AND sas.ISDELETED = 0 AND sas.ISACTIVED = 1
        )
    ) WHERE rn = 1
  ),
  -- Hợp đồng theo kho
  SA2 (SERVICEAGREEMENTID, PARTNERID, FEEAPPENDIXID, PNSERVICEPRICETABLEID, STOREID, rn) AS (
    SELECT * FROM (
      SELECT sa.SERVICEAGREEMENTID, sa.PARTNERID, saa.FEEAPPENDIXID, saa.PNSERVICEPRICETABLEID,
             sas.STOREID,
             ROW_NUMBER() OVER (PARTITION BY sa.PARTNERID, sas.STOREID ORDER BY saa.APPLYFROMDATE DESC) AS rn
      FROM TMS.TMS_SERVICEAGREEMENT sa
      JOIN TMS.TMS_SERVICEAGREEMENT_STORE sas ON sa.SERVICEAGREEMENTID = sas.SERVICEAGREEMENTID
      JOIN TMS.TMS_SERVICEAGREEMENT_APPENDIX saa ON sa.SERVICEAGREEMENTID = saa.SERVICEAGREEMENTID
      WHERE sa.ISDELETED = 0 AND sa.ISACTIVED = 1
        AND sas.ISDELETED = 0 AND sas.ISACTIVED = 1
        AND saa.ISDELETED = 0 AND saa.ISACTIVED = 1
        AND sa.SIGNEDDATE < v_END_DATE
        AND NVL(sa.EXTENDEDDATE, sa.EXPIREDDATE) >= v_START_DATE
        AND saa.APPLYTODATE >= v_START_DATE AND saa.APPLYFROMDATE < v_END_DATE
    ) WHERE rn = 1
  ),
  -- Bảng giá dịch vụ từng loại
  PRICETABLE_PRODUCT (
    PNSERVICEPRICETABLEDETAILID, PNSERVICEPRICETABLEID, PRODUCTID, SERVICEPRICE, ISCHECKMINQUANTITY, REWARDABLEMINQUANTITY
  ) AS (
    SELECT pt.PNSERVICEPRICETABLEDETAILID, pt.PNSERVICEPRICETABLEID, pt.PRODUCTID, pt.SERVICEPRICE, pt.ISCHECKMINQUANTITY, pt.REWARDABLEMINQUANTITY
    FROM TMS.TMS_PNSERVICEPRICETABLE p
    JOIN TMS.TMS_PNSERVICEPRICETABLEDETAIL pt ON p.PNSERVICEPRICETABLEID = pt.PNSERVICEPRICETABLEID
    WHERE p.ISDELETED = 0 AND p.ISACTIVED = 1 AND pt.PRODUCTID IS NOT NULL
  ),
  PRICETABLE_TECHSPECS (
    PNSERVICEPRICETABLEDETAILID, PNSERVICEPRICETABLEID, PRODUCTID, SERVICEPRICE, ISCHECKMINQUANTITY, REWARDABLEMINQUANTITY
  ) AS (
    SELECT pt.PNSERVICEPRICETABLEDETAILID, pt.PNSERVICEPRICETABLEID, prod.PRODUCTID, pt.SERVICEPRICE, pt.ISCHECKMINQUANTITY, pt.REWARDABLEMINQUANTITY
    FROM TMS.TMS_PNSERVICEPRICETABLE p
    JOIN TMS.TMS_PNSERVICEPRICETABLEDETAIL pt ON p.PNSERVICEPRICETABLEID = pt.PNSERVICEPRICETABLEID
    JOIN MASTERDATA.PM_PRODUCT prod ON pt.SUBGROUPID = prod.SUBGROUPID
    JOIN MASTERDATA.PM_PRODUCT_TECHSPECS ts ON prod.PRODUCTID = ts.PRODUCTID AND ts.TECHSPECSID = pt.TECHSPECSID AND ts.TECHSPECSVALUEID = pt.TECHSPECSVALUEID
    WHERE p.ISDELETED = 0 AND p.ISACTIVED = 1 AND pt.ISPRICEBYTECHSPECSVALUERANGE = 0 AND pt.TECHSPECSID > 0 AND pt.TECHSPECSVALUEID > 0
  ),
  PRICETABLE_TECHSPECS_RANGE (
    PNSERVICEPRICETABLEDETAILID, PNSERVICEPRICETABLEID, PRODUCTID, SERVICEPRICE, ISCHECKMINQUANTITY, REWARDABLEMINQUANTITY
  ) AS (
    SELECT pt.PNSERVICEPRICETABLEDETAILID, pt.PNSERVICEPRICETABLEID, prod.PRODUCTID, pt.SERVICEPRICE, pt.ISCHECKMINQUANTITY, pt.REWARDABLEMINQUANTITY
    FROM TMS.TMS_PNSERVICEPRICETABLE p
    JOIN TMS.TMS_PNSERVICEPRICETABLEDETAIL pt ON p.PNSERVICEPRICETABLEID = pt.PNSERVICEPRICETABLEID
    JOIN MASTERDATA.PM_PRODUCT prod ON pt.SUBGROUPID = prod.SUBGROUPID
    JOIN MASTERDATA.PM_PRODUCT_TECHSPECS ts ON prod.PRODUCTID = ts.PRODUCTID AND ts.TECHSPECSID = pt.TECHSPECSID
    JOIN MASTERDATA.PM_TECHSPECSVALUE tsv ON ts.TECHSPECSVALUEID = tsv.TECHSPECSVALUEID AND tsv.COMPAREVALUE >= pt.FROMTECHSPECSVALUE AND tsv.COMPAREVALUE <= pt.TOTECHSPECSVALUE
    WHERE p.ISDELETED = 0 AND p.ISACTIVED = 1 AND pt.ISPRICEBYTECHSPECSVALUERANGE = 1 AND pt.TECHSPECSID > 0 AND pt.TECHSPECSVALUEID < 1
  ),
  PRICETABLE_SUBGROUP (
    PNSERVICEPRICETABLEDETAILID, PNSERVICEPRICETABLEID, PRODUCTID, SERVICEPRICE, ISCHECKMINQUANTITY, REWARDABLEMINQUANTITY
  ) AS (
    SELECT pt.PNSERVICEPRICETABLEDETAILID, pt.PNSERVICEPRICETABLEID, prod.PRODUCTID, pt.SERVICEPRICE, pt.ISCHECKMINQUANTITY, pt.REWARDABLEMINQUANTITY
    FROM TMS.TMS_PNSERVICEPRICETABLE p
    JOIN TMS.TMS_PNSERVICEPRICETABLEDETAIL pt ON p.PNSERVICEPRICETABLEID = pt.PNSERVICEPRICETABLEID
    JOIN MASTERDATA.PM_PRODUCT prod ON pt.SUBGROUPID = prod.SUBGROUPID
    WHERE p.ISDELETED = 0 AND p.ISACTIVED = 1 AND pt.TECHSPECSID < 1 AND pt.TECHSPECSVALUEID < 1 AND TRIM(pt.PRODUCTID) IS NULL AND pt.SUBGROUPID > 0
  ),
  PRICETABLE_MAINGROUP (
    PNSERVICEPRICETABLEDETAILID, PNSERVICEPRICETABLEID, PRODUCTID, SERVICEPRICE, ISCHECKMINQUANTITY, REWARDABLEMINQUANTITY
  ) AS (
    SELECT pt.PNSERVICEPRICETABLEDETAILID, pt.PNSERVICEPRICETABLEID, prod.PRODUCTID, pt.SERVICEPRICE, pt.ISCHECKMINQUANTITY, pt.REWARDABLEMINQUANTITY
    FROM TMS.TMS_PNSERVICEPRICETABLE p
    JOIN TMS.TMS_PNSERVICEPRICETABLEDETAIL pt ON p.PNSERVICEPRICETABLEID = pt.PNSERVICEPRICETABLEID
    JOIN MASTERDATA.PM_SUBGROUP sg ON pt.MAINGROUPID = sg.MAINGROUPID
    JOIN MASTERDATA.PM_PRODUCT prod ON sg.SUBGROUPID = prod.SUBGROUPID
    WHERE p.ISDELETED = 0 AND p.ISACTIVED = 1 AND pt.TECHSPECSID < 1 AND pt.TECHSPECSVALUEID < 1 AND TRIM(pt.PRODUCTID) IS NULL AND pt.SUBGROUPID < 1 AND pt.MAINGROUPID > 0
  ),
  PRICETABLE_ALL (
    PNSERVICEPRICETABLEDETAILID, PNSERVICEPRICETABLEID, PRODUCTID, SERVICEPRICE, ISCHECKMINQUANTITY, REWARDABLEMINQUANTITY
  ) AS (
    SELECT * FROM PRICETABLE_PRODUCT
    UNION ALL
    SELECT * FROM PRICETABLE_TECHSPECS
    UNION ALL
    SELECT * FROM PRICETABLE_TECHSPECS_RANGE
    UNION ALL
    SELECT * FROM PRICETABLE_SUBGROUP
    UNION ALL
    SELECT * FROM PRICETABLE_MAINGROUP
  ),
  -- Dữ liệu giao hàng
  SHIPPING (
    PAYABLEDATE, PARTNERID, AREAID, STOREID, SHIPMENTORDERID, PARTNERSALEORDERID, DELIVERUSERFULLNAMELIST, SHIPMENTORDERITEMID, PRODUCTID, QUANTITY, SERVICEAGREEMENTID, FEEAPPENDIXID, PNSERVICEPRICETABLEID
  ) AS (
    SELECT 
      TRUNC(so.COMPLETEDELIVERIEDTIME, 'DD') AS PAYABLEDATE,
      so.CARRIERPARTNERID AS PARTNERID,
      msa.AREAID, so.COORDINATORSTOREID AS STOREID,
      so.SHIPMENTORDERID, so.PARTNERSALEORDERID, so.DELIVERUSERFULLNAMELIST, soi.SHIPMENTORDERITEMID, soi.PRODUCTID, soi.QUANTITY,
      NVL(sa2.SERVICEAGREEMENTID, sa.SERVICEAGREEMENTID) AS SERVICEAGREEMENTID,
      NVL(sa2.FEEAPPENDIXID, sa.FEEAPPENDIXID) AS FEEAPPENDIXID,
      NVL(sa2.PNSERVICEPRICETABLEID, sa.PNSERVICEPRICETABLEID) AS PNSERVICEPRICETABLEID
    FROM TMS.TMS_SHIPMENTORDER so
    JOIN TMS.TMS_SHIPMENTORDER_ITEM soi ON so.SHIPMENTORDERID = soi.SHIPMENTORDERID
    JOIN MDM.MD_STORE_AREA msa ON so.COORDINATORSTOREID = msa.STOREID AND msa.ISDELETED = 0
    JOIN MDM.MD_AREA ma ON ma.AREAID = msa.AREAID 
        AND ma.ISDELETED = 0
        AND ma.AREATYPEID = CASE 
            WHEN so.SHIPMENTORDERTYPEID IN (
                SELECT CAST(COLUMN_VALUE AS NUMBER(10))
                FROM TABLE(TMS.SPLIT(t_TMSCONFIGVALUE, ','))
                WHERE COLUMN_VALUE IS NOT NULL
            ) THEN 4 ELSE 1 END
    LEFT JOIN SA sa ON so.CARRIERPARTNERID = sa.PARTNERID AND msa.AREAID = sa.AREAID
    LEFT JOIN SA2 sa2 ON so.CARRIERPARTNERID = sa2.PARTNERID AND so.COORDINATORSTOREID = sa2.STOREID
    WHERE so.ISDELETED = 0 AND soi.ISDELETED = 0
      AND so.ISCOMPLETEDELIVERIED = 1 AND so.ISCANCELDELIVERY = 0
      AND soi.ISINSTALLITEM = 1 AND so.CARRIERPARTNERID > 0
      AND so.COMPLETEDELIVERIEDTIME >= v_START_DATE AND so.COMPLETEDELIVERIEDTIME < v_END_DATE
      AND (v_PARTNERID IS NULL OR so.CARRIERPARTNERID = v_PARTNERID)
      AND (v_STOREID IS NULL OR so.COORDINATORSTOREID IN (SELECT CAST(COLUMN_VALUE AS NUMBER(10))
                FROM TABLE (TMS.SPLIT(v_STOREID, ','))
                WHERE COLUMN_VALUE IS NOT NULL))
      AND NOT EXISTS (
        SELECT 1 FROM TMS.TMS_PAYABLETOPARTNERDETAIL ptpd 
        WHERE ptpd.SHIPMENTORDERID = so.SHIPMENTORDERID AND PTPD.ISDELETED = 0 AND PTPD.STOREID = V_STOREID
      )
  ),
  -- Dữ liệu vật tư
  MATERIAL (
    PAYABLEDATE, PARTNERID, AREAID, STOREID, SHIPMENTORDERID, PARTNERSALEORDERID, DELIVERUSERFULLNAMELIST, SHIPMENTORDERITEMID, PRODUCTID, QUANTITY, SERVICEAGREEMENTID, FEEAPPENDIXID, PNSERVICEPRICETABLEID
  ) AS (
    SELECT 
      TRUNC(so.COMPLETEDELIVERIEDTIME, 'DD') AS PAYABLEDATE,
      so.CARRIERPARTNERID AS PARTNERID,
      msa.AREAID, so.COORDINATORSTOREID AS STOREID,
      so.SHIPMENTORDERID, so.PARTNERSALEORDERID, so.DELIVERUSERFULLNAMELIST, som.SHIPMENTORDERMATERIALID AS SHIPMENTORDERITEMID,
      som.PRODUCTID, som.USAGEQUANTITY AS QUANTITY,
      NVL(sa2.SERVICEAGREEMENTID, sa.SERVICEAGREEMENTID) AS SERVICEAGREEMENTID,
      NVL(sa2.FEEAPPENDIXID, sa.FEEAPPENDIXID) AS FEEAPPENDIXID,
      NVL(sa2.PNSERVICEPRICETABLEID, sa.PNSERVICEPRICETABLEID) AS PNSERVICEPRICETABLEID
    FROM TMS.TMS_SHIPMENTORDER so
    JOIN TMS.TMS_SHIPMENTORDER_MATERIAL2 som ON so.SHIPMENTORDERID = som.SHIPMENTORDERID
    JOIN MDM.MD_STORE_AREA msa ON so.COORDINATORSTOREID = msa.STOREID AND msa.ISDELETED = 0
    JOIN MDM.MD_AREA ma ON ma.AREAID = msa.AREAID 
        AND ma.ISDELETED = 0
        AND ma.AREATYPEID = CASE 
            WHEN so.SHIPMENTORDERTYPEID IN (
                SELECT CAST(COLUMN_VALUE AS NUMBER(10))
                FROM TABLE(TMS.SPLIT(t_TMSCONFIGVALUE, ','))
                WHERE COLUMN_VALUE IS NOT NULL
            ) THEN 4 ELSE 1 END
    LEFT JOIN SA sa ON so.CARRIERPARTNERID = sa.PARTNERID AND msa.AREAID = sa.AREAID
    LEFT JOIN SA2 sa2 ON so.CARRIERPARTNERID = sa2.PARTNERID AND so.COORDINATORSTOREID = sa2.STOREID
    WHERE so.ISDELETED = 0 AND som.ISDELETED = 0
      AND so.ISCOMPLETEDELIVERIED = 1 AND so.ISCANCELDELIVERY = 0
      AND so.CARRIERPARTNERID > 0 AND som.USAGEQUANTITY > 0
      AND so.COMPLETEDELIVERIEDTIME >= v_START_DATE AND so.COMPLETEDELIVERIEDTIME < v_END_DATE
      AND (v_PARTNERID IS NULL OR so.CARRIERPARTNERID = v_PARTNERID)
      AND (v_STOREID IS NULL OR so.COORDINATORSTOREID IN (SELECT CAST(COLUMN_VALUE AS NUMBER(10))
                FROM TABLE (TMS.SPLIT(v_STOREID, ','))
                WHERE COLUMN_VALUE IS NOT NULL))
      AND NOT EXISTS (
        SELECT 1 FROM TMS.TMS_PAYABLETOPARTNERDETAIL ptpd 
        WHERE ptpd.SHIPMENTORDERID = so.SHIPMENTORDERID AND PTPD.ISDELETED = 0 AND PTPD.STOREID = V_STOREID
      )
  )
  -- Trả kết quả
  SELECT s.PAYABLEDATE, s.PARTNERID, s.SHIPMENTORDERID, s.PARTNERSALEORDERID, s.SHIPMENTORDERITEMID,
         s.PRODUCTID, s.DELIVERUSERFULLNAMELIST AS DELIVERYUSER,
         NVL(pt.SERVICEPRICE, 0) AS SERVICEFEE,
         s.QUANTITY,
         NVL(pt.SERVICEPRICE, 0) * s.QUANTITY AS PAYABLEAMOUNT,
         s.SERVICEAGREEMENTID, s.AREAID, s.STOREID,
         s.FEEAPPENDIXID, pt.PNSERVICEPRICETABLEDETAILID,
         s.PNSERVICEPRICETABLEID,
         'administrator', SYSDATE
  FROM SHIPPING s
  LEFT JOIN PRICETABLE_ALL pt ON s.PRODUCTID = pt.PRODUCTID AND s.PNSERVICEPRICETABLEID = pt.PNSERVICEPRICETABLEID
  UNION ALL
  SELECT m.PAYABLEDATE, m.PARTNERID, m.SHIPMENTORDERID, m.PARTNERSALEORDERID, m.SHIPMENTORDERITEMID,
         m.PRODUCTID, m.DELIVERUSERFULLNAMELIST AS DELIVERYUSER,
         NVL(pt.SERVICEPRICE, 0) AS SERVICEFEE,
         GREATEST(m.QUANTITY - NVL(pt.REWARDABLEMINQUANTITY, 0), 0),
         NVL(pt.SERVICEPRICE, 0) * GREATEST(m.QUANTITY - NVL(pt.REWARDABLEMINQUANTITY, 0), 0),
         m.SERVICEAGREEMENTID, m.AREAID, m.STOREID,
         m.FEEAPPENDIXID, pt.PNSERVICEPRICETABLEDETAILID,
         m.PNSERVICEPRICETABLEID,
         'administrator', SYSDATE
  FROM MATERIAL m
  LEFT JOIN PRICETABLE_ALL pt ON m.PRODUCTID = pt.PRODUCTID AND m.PNSERVICEPRICETABLEID = pt.PNSERVICEPRICETABLEID;
END;
/