CREATE OR REPLACE PROCEDURE TMS.TMS_STAFFDEBT_CLEARDEBT
  /*
    Mô tả: store cập nhật bảng xóa công nợ của nhân viên
    Người tạo: Nguyen Trung Hieu
    Ngày tạo: 07/07/2025 
  */

(
    v_USERNAME TMS.TMS_STAFFDEBT.USERNAME%type,
    v_STOREID TMS.TMS_STAFFDEBT.STOREID%type,
    v_SHIPMENTORDERID TMS.TMS_SHIPMENTORDER.SHIPMENTORDERID%type
   
)
AS
t_TOTALCOD TMS.TMS_STAFFDEBTDETAIL.TOTALCOD%TYPE;
t_TOTALSALEMATERIALMONEY TMS.TMS_STAFFDEBTDETAIL.TOTALSALEMATERIALMONEY%TYPE;
t_TOTALMONEY TMS.TMS_STAFFDEBTDETAIL.TOTALMONEY%TYPE;
t_COLLECTEDTOTALMONEY TMS.TMS_STAFFDEBTDETAIL.COLLECTEDTOTALMONEY%TYPE;
t_TOTALDEBTORDERS TMS.TMS_STAFFDEBTDETAIL.TOTALDEBTORDERS%TYPE;
t_TOTALOVERDUEDEBTORDERS TMS.TMS_STAFFDEBTDETAIL.TOTALOVERDUEDEBTORDERS%TYPE;
t_TOTALTRUCKCOD TMS.TMS_STAFFDEBTDETAIL.TOTALTRUCKCOD%TYPE;
t_TOTALMOTOCYCLECOD TMS.TMS_STAFFDEBTDETAIL.TOTALMOTOCYCLECOD%TYPE;
BEGIN
  BEGIN
    SELECT
      NVL(SUM(TOTALCOD),0),
      NVL(SUM(TOTALSALEMATERIALMONEY),0),
      NVL(SUM(TOTALMONEY),0),
      NVL(SUM(COLLECTEDTOTALMONEY),0),
      COUNT(*),
      NVL(SUM(ISLOCKDELIVERY),0),
      NVL(SUM(CASE WHEN CARRIERTYPEID = 2 AND ISUNLOCKDELIVERY = 0 THEN TOTALCOD ELSE 0 END),0),
      NVL(SUM(CASE WHEN CARRIERTYPEID = 1 AND ISUNLOCKDELIVERY = 0 THEN TOTALCOD ELSE 0 END),0)
    INTO
      t_TOTALCOD, t_TOTALSALEMATERIALMONEY, t_TOTALMONEY, t_COLLECTEDTOTALMONEY,
      t_TOTALDEBTORDERS, t_TOTALOVERDUEDEBTORDERS, t_TOTALTRUCKCOD, t_TOTALMOTOCYCLECOD
    FROM TMS.TMS_STAFFDEBTDETAIL
    WHERE USERNAME = v_USERNAME AND STOREID = v_STOREID
    GROUP BY USERNAME, STOREID;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      t_TOTALCOD := 0;
      t_TOTALSALEMATERIALMONEY := 0;
      t_TOTALMONEY := 0;
      t_COLLECTEDTOTALMONEY := 0;
      t_TOTALDEBTORDERS := 0;
      t_TOTALOVERDUEDEBTORDERS := 0;
      t_TOTALTRUCKCOD := 0;
      t_TOTALMOTOCYCLECOD := 0;
  END;
  
  DELETE FROM TMS.TMS_STAFFDEBTDETAIL
    WHERE SHIPMENTORDERID = V_SHIPMENTORDERID AND USERNAME = V_USERNAME AND STOREID = V_STOREID;
  
  UPDATE TMS.TMS_SHIPMENTORDER
    SET TOTALUNPAIDINMONEY = 0
    WHERE SHIPMENTORDERID = V_SHIPMENTORDERID;
  
  UPDATE TMS.TMS_STAFFDEBT SET
    TOTALCOD = t_TOTALCOD,
    TOTALSALEMATERIALMONEY = t_TOTALSALEMATERIALMONEY,
    TOTALMONEY = t_TOTALMONEY,
    COLLECTEDTOTALMONEY = t_COLLECTEDTOTALMONEY,
    TOTALDEBTORDERS = t_TOTALDEBTORDERS,
    TOTALOVERDUEDEBTORDERS = t_TOTALOVERDUEDEBTORDERS ,
    TOTALTRUCKCOD = t_TOTALTRUCKCOD,
    TOTALMOTOCYCLECOD = t_TOTALMOTOCYCLECOD
  WHERE USERNAME = v_USERNAME
  AND STOREID = v_STOREID;
  
  

  
END;
/