CREATE OR REPLACE PROCEDURE TMS.TMS_SHIPCOORDIGR_MEM_BYID
   /*
    Mô tả: store lấy một danh sách các trưởng nhóm thuộc nhóm điều phối theo COORDINATORGROUPID theo vận đơn
    Người tạo: Ngruyen Trung Hieu
    Ngày tạo: 18/07/2025 15:52
    
  */
(
    v_Out OUT SYS_REFCURSOR,
    v_SHIPMENTORDERID IN TMS.TMS_SHIPMENTORDER.SHIPMENTORDERID%TYPE
)
AS
BEGIN
  OPEN v_Out FOR

  SELECT
        MD_COORDINATORGROUP_MEMBER.USERNAME,
        MSU.FULLNAME,
        TS.SHIPMENTORDERID, 
        TS.COORDINATORSTOREID
      
       
  FROM TMS.TMS_SHIPMENTORDER TS 
   JOIN MDM.MD_COORDINATORGROUP_DAREA MDA 
    ON MDA.COORDINATORSTOREID = TS.COORDINATORSTOREID AND MDA.ISDELETED = 0
   JOIN MDM.MD_COORDINATORGROUP_MEMBER  
    ON MDA.COORDINATORGROUPID = MD_COORDINATORGROUP_MEMBER.COORDINATORGROUPID
   JOIN MASTERDATA.SYSTEM_USER MSU 
    ON MSU.USERNAME = MD_COORDINATORGROUP_MEMBER.USERNAME AND MSU.ISDELETE = 0
  
  WHERE TS.SHIPMENTORDERID = v_SHIPMENTORDERID AND TS.ISDELETED = 0 AND MD_COORDINATORGROUP_MEMBER.USERNAME IS NOT NULL
  
  GROUP BY 
        MD_COORDINATORGROUP_MEMBER.USERNAME,
        MSU.FULLNAME,
        TS.SHIPMENTORDERID, 
        TS.COORDINATORSTOREID
  ;
END;
/